### ISSUE TITLE
[Code Quality] Incomplete Repo information

### ISSUE THREAD

**Issue by Haydnspass** [mackelab/python-intro#1]
Your repo does not comply to the standards we defined in the lab. 
Make sure for your repo to have:
- [x] a description including the github handle of the owner
- [x] a > 3 line README.md

If you don't update your repo, it will be disabled and then archived.

**Comment by alcrene** [comment]
Done, although if the lab still intends to use this repo, it probably makes more sense to assign an active member as maintainer.
I think the tutorial content was pretty good work, but it was definitely just an initial version, and doesn’t seem like it’s been used much since we made it – possibly nowadays everyone shows up with some Python experience. If it’s never going to be used again, maybe it should just be archived.
